[package]
name = "kes"
version = "0.0.2"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
description = "Korean Era Script"
license = "MIT"
documentation = "https://docs.rs/kes"
homepage = "https://github.com/Riey/kes-rs"
repository = "https://github.com/Riey/kes-rs"
readme = "README.md"

[[bench]]
name = "parse"
harness = false

[profile.release]
debug = true

[dependencies]
memchr = "2.3.0"
bumpalo = { version = "3.2.0", features = ["collections"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3.1"
