[package]
name = "kes"
version = "0.10.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
description = "Korean Era Script"
license = "MIT"
documentation = "https://docs.rs/kes"
homepage = "https://github.com/Riey/kes-rs"
repository = "https://github.com/Riey/kes-rs"
readme = "README.md"

[features]
logging = ["log"]
unstable = []

[profile.release]
debug = true

[dependencies]
memchr = "2.3.2"
bumpalo = { version = "3.2.1", features = ["collections"] }
ahash = "0.3.2"
thiserror = "1.0.11"
async-trait = "0.1.24"
log = { version = "0.4.8", optional = true }
arrayvec = "0.5.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
futures = "0.3.4"
