[package]
name = "kes-rs"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.26"
bumpalo = { version = "3.1.2", features = ["collections"] }
twoway = "0.2.1"
memchr = "2.3.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
