[package]
name = "kes"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[[bench]]
name = "parse"
harness = false

[dependencies]
memchr = "2.3.0"
bumpalo = { version = "3.2.0", features = ["collections"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3.1"
